# Generated by Django 5.1.3 on 2024-11-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agency_user_account_user_bank_user_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cci',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='user',
            name='polo_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shoe_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yaple_plin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zone',
        ),
    ]
