# Generated by Django 5.1.3 on 2024-11-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_account_remove_user_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_user', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cci',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='polo_size',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='shoe_size',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='yaple_plin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
