# Generated by Django 5.1.3 on 2024-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_delete_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
