# Generated by Django 5.1.3 on 2024-11-26 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_agency_user_account_user_bank_user_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('other', models.CharField(max_length=70)),
                ('paid_date', models.DateField()),
                ('materials_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('passage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labour_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('1', 'atendida'), ('2', 'asignada'), ('3', 'confirmada'), ('4', 'denegada')], default='1', max_length=1)),
                ('sub_state', models.CharField(choices=[('1', 'pendiente conformidad y registro confirmado')], default='1', max_length=1)),
                ('observation', models.CharField(choices=[('1', 'SIN ASIGNAR'), ('2', 'ATS'), ('3', 'COMPLETO'), ('4', 'COTIZACION'), ('5', 'INFORME')], default='1', max_length=1)),
                ('description', models.TextField(max_length=500)),
                ('payment', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_ticket', to='accounts.agency')),
                ('asigner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_technical', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('if_other', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('other_description', models.TextField(max_length=500)),
                ('calification', models.CharField(choices=[('1', 'BUENO'), ('2', 'REGULAR'), ('3', 'MALO')], default='1', max_length=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_facture', to='tickets.service')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_facture', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
    ]
