# Generated by Django 5.1.3 on 2024-11-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
